version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
    env_file:
      - .env

  product_service:
    build:
      context: ./product_service
    ports:
      - "8002:8000"
    env_file:
      - .env

  order_service:
    build:
      context: ./order_service
    ports:
      - "8003:8000"
    env_file:
      - .env

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:80"
    depends_on:
      - user_service
      - product_service
      - order_service
    env_file:
      - .env
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf  # Map nginx.conf
    command: nginx -g 'daemon off;'
