"""
Django settings for user_service project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j%vc)n=o1ktuqjv!o(gg7+($tgh12=!v0sodl3%j^sxca^l6wg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = []  # Add your domain or IP address here in production


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "authentication",  # Your custom authentication app
    "rest_framework",
    "rest_framework.authtoken",  # DRF Token authentication
    'django.contrib.sites',  # Required by Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # Enable social logins if required
    "verify_email.apps.VerifyEmailConfig",  # Email verification app
]

# Django Rest Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
     'allauth.account.middleware.AccountMiddleware', 
]

ROOT_URLCONF = "user_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/'Templates'],  # Set your custom templates directory
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "user_service.wsgi.application"


# Database
# Default database is SQLite3. Replace with PostgreSQL or MySQL in production.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Static files directory
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Collect static files in production


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Security settings for CSRF and session management
CSRF_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = False  # False since we might grab it via universal-cookies
SESSION_COOKIE_HTTPONLY = True

# Use the following settings in production:
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Redirect to login page if not authenticated
LOGIN_URL = '/authentication/login/'


# Email configuration for sending email verifications
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'issackondreddy@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'qhvm yuqz dune qywj'  # Replace with your app password

DEFAULT_FROM_EMAIL = 'issackondreddy@gmail.com'  
SITE_ID = 1  # Required for Django Allauth

# Account activation email configuration
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login' 
# Allauth email confirmation settings
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/home/'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'login'

# Email verification custom settings (Optional)
HTML_MESSAGE_TEMPLATE = "authentication/email_message.html"
VERIFICATION_SUCCESS_TEMPLATE = "authentication/success.html"
VERIFICATION_FAILED_TEMPLATE = "authentication/failed.html"

# Expire email verification link after 1 day
EXPIRE_AFTER = "1d"

# Allow the user to resend the email 3 times before limiting
MAX_RETRIES = 3
