# Generated by Django 5.0.3 on 2024-10-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userprofile_profile_picture"),
        ("authentication", "0004_auto_20241024_1358"),
    ]

    operations = []
