# Generated by Django 5.0.3 on 2024-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="price",
            new_name="product_price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_name",
            field=models.CharField(default="Sample Product", max_length=255),
            preserve_default=False,
        ),
    ]
