name: Django CI

on:
  push:
    branches:
      - master
      - dev
      - user-service
      - product-service
      - order-service
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: recommerce
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{POSTGRES_USER}}" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Django server (optional)
      run: |
        python manage.py runserver
